In [200]:
from functools import reduce
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 500)

In [201]:
##TODO: still need to filter out cities based on population

accidental_death = pd.read_csv('data/accidental_death/Compressed Mortality, 1999-2016.txt', sep='\t')
crime = pd.read_excel('data/crime/table-6.xls', header=3)
airq = pd.read_csv('data/air_quality/annual_aqi_by_cbsa_2018.csv')
population = pd.read_csv('data/population/ACS_17_1YR_B01003_with_ann.csv', header=1)
crosswalk = pd.read_excel('data/crosswalk/list1_Sep_2018.xls',header=2)
smoking_drinking = pd.read_csv('data/smoking_drinking/Behavioral_Risk_Factors__Selected_Metropolitan_Area_Risk_Trends__SMART__MMSA_Prevalence_Data__2011_to_Present_.csv')

In [202]:
accidental_death

,Notes,2013 CBSA,2013 CBSA Code,Deaths,Population,Crude Rate,Age Adjusted Rate
0,NaN,"Akron, OH",10420.0,4879.0,12625850.0,38.6,36.8
1,NaN,"Albany-Schenectady-Troy, NY",10580.0,3818.0,15466849.0,24.7,22.5
2,NaN,"Albuquerque, NM",10740.0,9101.0,15049954.0,60.5,60.7
3,NaN,"Allentown-Bethlehem-Easton, PA-NJ",10900.0,5955.0,14352019.0,41.5,37.5
4,NaN,"Amarillo, TX",11100.0,1986.0,4424674.0,44.9,45.5
5,NaN,"Anchorage, AK",11260.0,2902.0,6547472.0,44.3,49.3
6,NaN,"Ann Arbor, MI",11460.0,1613.0,6179200.0,26.1,28.1
7,NaN,"Asheville, NC",11700.0,4152.0,7379094.0,56.3,49.3
8,NaN,"Atlanta-Sandy Springs-Roswell, GA",12060.0,31056.0,90449335.0,34.3,38.0
9,NaN,"Atlantic City-Hammonton, NJ",12100.0,2204.0,4830144.0,45.6,44.2
10,NaN,"Augusta-Richmond County, GA-SC",12260.0,4433.0,9876079.0,44.9,45.4
11,NaN,"Austin-Round Rock, TX",12420.0,10118.0,28983975.0,34.9,39.6
12,NaN,"Bakersfield, CA",12540.0,6231.0,14181056.0,43.9,47.6
13,NaN,"Baltimore-Columbia-Towson, MD",12580.0,13500.0,48206323.0,28.0,27.3
14,NaN,"Baton Rouge, LA",12940.0,6503.0,13890020.0,46.8,48.1
15,NaN,"Beaumont-Port Arthur, TX",13140.0,3777.0,7225487.0,52.3,51.9
16,NaN,"Birmingham-Hoover, AL",13820.0,10581.0,19871028.0,53.2,52.7
17,NaN,"Boise City, ID",14260.0,3571.0,10427242.0,34.2,35.7
18,NaN,"Boston-Cambridge-Newton, MA-NH",14460.0,24763.0,81601562.0,30.3,28.5
19,NaN,"Boulder, CO",14500.0,2197.0,5340377.0,41.1,45.3
20,NaN,"Bremerton-Silverdale, WA",14740.0,1596.0,4433423.0,36.0,35.0
21,NaN,"Bridgeport-Stamford-Norwalk, CT",14860.0,5160.0,16394845.0,31.5,29.7
22,NaN,"Brownsville-Harlingen, TX",15180.0,1571.0,6929145.0,22.7,24.4
23,NaN,"Buffalo-Cheektowaga-Niagara Falls, NY",15380.0,6413.0,20634485.0,31.1,28.1
24,NaN,"Canton-Massillon, OH",15940.0,3039.0,7287867.0,41.7,37.6
25,NaN,"Cape Coral-Fort Myers, FL",15980.0,6203.0,10452739.0,59.3,52.6
26,NaN,"Cedar Rapids, IA",16300.0,1733.0,4545321.0,38.1,35.8
27,NaN,"Charleston-North Charleston, SC",16700.0,4992.0,11505391.0,43.4,44.1
28,NaN,"Charlotte-Concord-Gastonia, NC-SC",16740.0,14988.0,37458020.0,40.0,41.8
29,NaN,"Chattanooga, TN-GA",16860.0,4358.0,9249007.0,47.1,45.5
...,...,...,...,...,...,...,...
221,population figures for 2001-2009 are from the ...,NaN,NaN,NaN,NaN,NaN,NaN
222,resident population; population figures for 20...,NaN,NaN,NaN,NaN,NaN,NaN
223,the Vintage 2011 series released by NCHS on Ju...,NaN,NaN,NaN,NaN,NaN,NaN
224,"the July 1 resident population, from the Vinta...",NaN,NaN,NaN,NaN,NaN,NaN
225,bridged-race postcensal estimates of the July ...,NaN,NaN,NaN,NaN,NaN,NaN
226,2014; population figures for 2014 are bridged-...,NaN,NaN,NaN,NaN,NaN,NaN
227,"series released by NCHS on June 30, 2015. and ...",NaN,NaN,NaN,NaN,NaN,NaN
228,"resident population, from the Vintage 2015 ser...",NaN,NaN,NaN,NaN,NaN,NaN
229,http://wonder.cdc.gov/wonder/help/cmf.html#Pop...,NaN,NaN,NaN,NaN,NaN,NaN
230,2. The population figures used in the calculat...,NaN,NaN,NaN,NaN,NaN,NaN
231,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN
232,3. The populations used to calculate standard ...,NaN,NaN,NaN,NaN,NaN,NaN
233,http://wonder.cdc.gov/wonder/help/cmf.html#200...,NaN,NaN,NaN,NaN,NaN,NaN
234,4. The method used to calculate age-adjusted r...,NaN,NaN,NaN,NaN,NaN,NaN
235,http://wonder.cdc.gov/wonder/help/cmf.html#Age...,NaN,NaN,NaN,NaN,NaN,NaN
236,5. Deaths for persons of unknown age are inclu...,NaN,NaN,NaN,NaN,NaN,NaN
237,"6. As of April 3, 2017, the underlying cause o...",NaN,NaN,NaN,NaN,NaN,NaN
238,http://wonder.cdc.gov/wonder/help/cmf.html#201...,NaN,NaN,NaN,NaN,NaN,NaN
239,7. 2013 CBSA shows data for core based statist...,NaN,NaN,NaN,NaN,NaN,NaN
240,classification of counties as metropolitan or ...,NaN,NaN,NaN,NaN,NaN,NaN
241,8. Circumstances in California resulted in unu...,NaN,NaN,NaN,NaN,NaN,NaN
242,ill-defined and unspecified causes of mortalit...,NaN,NaN,NaN,NaN,NaN,NaN
243,interpreting these data. More information: htt...,NaN,NaN,NaN,NaN,NaN,NaN
244,9. Circumstances in Georgia for the years 2008...,NaN,NaN,NaN,NaN,NaN,NaN
245,"code R99, ""Other ill-defined and unspecified c...",NaN,NaN,NaN,NaN,NaN,NaN
246,information: http://wonder.cdc.gov/wonder/help...,NaN,NaN,NaN,NaN,NaN,NaN
247,10. Circumstances in New Jersey for the year 2...,NaN,NaN,NaN,NaN,NaN,NaN
248,"code R99, ""Other ill-defined and unspecified c...",NaN,NaN,NaN,NaN,NaN,NaN
249,"codes, most notably R95, ""Sudden Infant Death ...",NaN,NaN,NaN,NaN,NaN,NaN
250,interpreting these data. More information: htt...,NaN,NaN,NaN,NaN,NaN,NaN

In [203]:
crime

,Metropolitan Statistical Area,Counties/principal cities,Population,Violent crime,Murder and nonnegligent manslaughter,Rape1,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft
0,"Abilene, TX M.S.A.2, 3",NaN,170995,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
1,NaN,"Includes Callahan, Jones, and Taylor Counties",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"City of Abilene2, 3",122981,636,4,100.0,138.0,394,NaN,NaN,2605.0,260.0
3,NaN,Total area actually reporting,1,753,7,120.0,143.0,483,NaN,NaN,2938.0,301.0
4,NaN,"Rate per 100,000 inhabitants",NaN,440.4,4.1,70.2,83.6,282.5,NaN,NaN,1718.2,176.0
5,"Akron, OH M.S.A.4",NaN,703907,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
6,NaN,Includes Portage4 and Summit Counties,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,City of Akron,197412,1377,42,209.0,395.0,731,8360,2301.0,5304.0,755.0
8,NaN,Total area actually reporting,0.963,1911,51,335.0,494.0,1031,17340,3681.0,12587.0,1072.0
9,NaN,Estimated total,1,1952,52,344.0,506.0,1050,17886,3764.0,13024.0,1098.0
10,NaN,"Rate per 100,000 inhabitants",NaN,277.3,7.4,48.9,71.9,149.2,2541,534.7,1850.2,156.0
11,"Albany, GA M.S.A.",NaN,151534,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
12,NaN,"Includes Baker, Dougherty, Lee, Terrell, and W...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,City of Albany,73209,827,22,27.0,152.0,626,4116,879.0,3048.0,189.0
14,NaN,Total area actually reporting,0.96,1079,23,55.0,186.0,815,5773,1229.0,4289.0,255.0
15,NaN,Estimated total,1,1101,23,57.0,192.0,829,5966,1259.0,4436.0,271.0
16,NaN,"Rate per 100,000 inhabitants",NaN,726.6,15.2,37.6,126.7,547.1,3937.1,830.8,2927.4,178.8
17,"Albany, OR M.S.A.2",NaN,124014,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
18,NaN,Includes Linn County2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,City of Albany2,53701,56,0,8.0,20.0,28,1406,158.0,1137.0,111.0
20,NaN,Total area actually reporting,1,196,2,41.0,26.0,127,3159,489.0,2368.0,302.0
21,NaN,"Rate per 100,000 inhabitants",NaN,158,1.6,33.1,21.0,102.4,2547.3,394.3,1909.5,243.5
22,"Albany-Schenectady-Troy, NY M.S.A.",NaN,885673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,"Includes Albany, Rensselaer, Saratoga, Schenec...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,City of Albany,98174,876,8,54.0,247.0,567,3394,432.0,2853.0,109.0
25,NaN,City of Schenectady,64710,577,2,58.0,141.0,376,2057,348.0,1534.0,175.0
26,NaN,City of Troy,49644,351,6,31.0,114.0,200,1732,370.0,1272.0,90.0
27,NaN,Total area actually reporting,1,2579,18,361.0,640.0,1560,17312,2279.0,14376.0,657.0
28,NaN,"Rate per 100,000 inhabitants",NaN,291.2,2,40.8,72.3,176.1,1954.7,257.3,1623.2,74.2
29,"Albuquerque, NM M.S.A.",NaN,915069,,NaN,NaN,NaN,NaN,,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
2308,NaN,"Includes Arecibo, Camuy, Hatillo, and Quebradi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2309,NaN,Total area actually reporting,1,321,15,9.0,92.0,205,1180,319.0,760.0,101.0
2310,NaN,"Rate per 100,000 inhabitants",NaN,176.7,8.3,5.0,50.6,112.9,649.6,175.6,418.4,55.6
2311,"Guayama, Puerto Rico M.S.A.",NaN,76166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2312,NaN,"Includes Arroyo, Guayama, and Patillas Municipios",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2313,NaN,Total area actually reporting,1,175,14,3.0,24.0,134,501,203.0,282.0,16.0
2314,NaN,"Rate per 100,000 inhabitants",NaN,229.8,18.4,3.9,31.5,175.9,657.8,266.5,370.2,21.0
2315,"Mayaguez, Puerto Rico M.S.A.",NaN,91557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2316,NaN,Includes Hormigueros and Mayaguez Municipios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2317,NaN,Total area actually reporting,1,163,10,6.0,45.0,102,820,165.0,617.0,38.0
2318,NaN,"Rate per 100,000 inhabitants",NaN,178,10.9,6.6,49.1,111.4,895.6,180.2,673.9,41.5
2319,"Ponce, Puerto Rico M.S.A.",NaN,300843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2320,NaN,"Includes Guanica, Guyanilla, Juana Diaz, Penue...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2321,NaN,Total area actually reporting,1,834,52,16.0,179.0,587,2289,522.0,1674.0,93.0
2322,NaN,"Rate per 100,000 inhabitants",NaN,277.2,17.3,5.3,59.5,195.1,760.9,173.5,556.4,30.9
2323,"San German, Puerto Rico M.S.A.",NaN,126097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2324,NaN,"Includes Cabo Rojo, Lajas, Sabana Grande, and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2325,NaN,Total area actually reporting,1,141,9,5.0,19.0,108,459,158.0,281.0,20.0
2326,NaN,"Rate per 100,000 inhabitants",NaN,111.8,7.1,4.0,15.1,85.6,364,125.3,222.8,15.9
2327,"San Juan-Carolina-Caguas, Puerto Rico M.S.A.",NaN,2112005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2328,NaN,"Includes Aguas Buenas, Aibonito, Barceloneta, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2329,NaN,Total area actually reporting,1,5380,539,147.0,2546.0,2148,23103,5524.0,14369.0,3210.0
2330,NaN,"Rate per 100,000 inhabitants",NaN,254.7,25.5,7.0,120.5,101.7,1093.9,261.6,680.3,152.0
2331,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2332,2 Because of changes in the state/local agency...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2333,3 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2334,4 One or more agency(s) wihin this Metropolita...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2335,5 The FBI determined that the agency's data we...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2336,6 The FBI determined that the agency did not f...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2337,"7 The population for the city of Mobile, Alaba...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [204]:
airq

,CBSA,CBSA Code,Year,Days with AQI,Good Days,Moderate Days,Unhealthy for Sensitive Groups Days,Unhealthy Days,Very Unhealthy Days,Hazardous Days,Max AQI,90th Percentile AQI,Median AQI,Days CO,Days NO2,Days Ozone,Days SO2,Days PM2.5,Days PM10
0,"Aberdeen, WA",10140,2018,31,30,1,0,0,0,0,57,38,26,0,0,0,0,31,0
1,"Akron, OH",10420,2018,90,71,19,0,0,0,0,79,60,37,0,0,27,0,63,0
2,"Albany, GA",10500,2018,59,44,15,0,0,0,0,79,64,29,0,0,0,0,59,0
3,"Albany-Schenectady-Troy, NY",10580,2018,90,69,21,0,0,0,0,78,60,40,0,0,52,0,38,0
4,"Alexandria, LA",10780,2018,28,26,2,0,0,0,0,54,49,27,0,0,0,0,28,0
5,"Amarillo, TX",11100,2018,59,59,0,0,0,0,0,48,44,37,0,0,59,0,0,0
6,"Ann Arbor, MI",11460,2018,58,58,0,0,0,0,0,44,38,32,0,0,58,0,0,0
7,"Appleton, WI",11540,2018,31,21,8,2,0,0,0,123,69,35,0,0,0,5,26,0
8,"Ardmore, OK",11620,2018,90,72,18,0,0,0,0,84,55,34,0,0,13,0,77,0
9,"Arkadelphia, AR",11660,2018,59,59,0,0,0,0,0,40,36,28,0,0,59,0,0,0
10,"Asheville, NC",11700,2018,90,50,21,13,6,0,0,199,135,43,0,0,0,44,46,0
11,"Ashtabula, OH",11780,2018,90,90,0,0,0,0,0,46,42,1,0,0,30,60,0,0
12,"Athens, OH",11900,2018,16,16,0,0,0,0,0,40,36,23,0,0,0,0,16,0
13,"Athens-Clarke County, GA",12020,2018,11,11,0,0,0,0,0,32,25,19,0,0,0,0,11,0
14,"Atlanta-Sandy Springs-Roswell, GA",12060,2018,59,43,16,0,0,0,0,63,58,42,0,6,11,0,42,0
15,"Augusta-Richmond County, GA-SC",12260,2018,120,86,34,0,0,0,0,90,61,44,0,0,71,2,47,0
16,"Augusta-Waterville, ME",12300,2018,119,113,6,0,0,0,0,87,48,37,0,42,66,1,8,2
17,"Bakersfield, CA",12540,2018,120,106,14,0,0,0,0,80,52,32,0,0,47,0,70,3
18,"Baltimore-Columbia-Towson, MD",12580,2018,90,58,32,0,0,0,0,85,64,44,0,6,30,4,50,0
19,"Bangor, ME",12620,2018,120,105,15,0,0,0,0,87,52,41,0,0,60,0,60,0
20,"Baraboo, WI",12660,2018,31,27,4,0,0,0,0,60,51,34,0,0,0,0,31,0
21,"Barnstable Town, MA",12700,2018,86,86,0,0,0,0,0,47,43,38,0,0,86,0,0,0
22,"Baton Rouge, LA",12940,2018,120,82,33,4,1,0,0,153,73,46,0,1,80,1,38,0
23,"Bay City, MI",13020,2018,1,1,0,0,0,0,0,22,22,22,0,0,0,0,1,0
24,"Beaver Dam, WI",13180,2018,36,31,5,0,0,0,0,61,56,32,0,0,13,0,18,5
25,"Bellingham, WA",13380,2018,31,22,8,1,0,0,0,104,69,35,0,0,0,15,16,0
26,"Bemidji, MN",13420,2018,88,83,5,0,0,0,0,58,43,25,0,0,0,0,88,0
27,"Birmingham-Hoover, AL",13820,2018,59,37,21,1,0,0,0,124,58,47,0,1,6,8,43,1
28,"Bishop, CA",13860,2018,88,86,2,0,0,0,0,71,46,40,0,0,84,0,0,4
29,"Bismarck, ND",13900,2018,88,69,18,1,0,0,0,122,62,40,0,1,47,0,40,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,"Utica-Rome, NY",46540,2018,90,84,6,0,0,0,0,56,48,39,0,0,59,0,31,0
287,"Valdosta, GA",46660,2018,49,43,6,0,0,0,0,74,52,36,0,0,0,0,49,0
288,"Vallejo-Fairfield, CA",46700,2018,89,68,20,1,0,0,0,132,63,39,0,1,46,0,42,0
289,"Vernal, UT",46860,2018,120,97,23,0,0,0,0,84,58,44,0,0,113,0,7,0
290,"Vincennes, IN",47180,2018,59,59,0,0,0,0,0,44,35,30,0,0,59,0,0,0
291,"Vineyard Haven, MA",47240,2018,87,87,0,0,0,0,0,45,44,39,0,0,87,0,0,0
292,"Virginia Beach-Norfolk-Newport News, VA-NC",47260,2018,29,27,2,0,0,0,0,65,40,21,0,0,0,0,20,9
293,"Visalia-Porterville, CA",47300,2018,90,82,8,0,0,0,0,74,50,37,0,0,90,0,0,0
294,"Wabash, IN",47340,2018,59,59,0,0,0,0,0,44,37,30,0,0,59,0,0,0
295,"Walla Walla, WA",47460,2018,31,29,2,0,0,0,0,58,44,21,0,0,0,0,27,4
296,"Walterboro, SC",47500,2018,120,110,10,0,0,0,0,72,49,37,0,0,97,0,23,0
297,"Warner Robins, GA",47580,2018,39,32,7,0,0,0,0,67,62,29,0,0,0,0,39,0
298,"Washington Court House, OH",47920,2018,59,59,0,0,0,0,0,44,37,31,0,0,59,0,0,0
299,"Washington, NC",47820,2018,90,90,0,0,0,0,0,17,7,0,0,0,0,90,0,0
300,"Washington-Arlington-Alexandria, DC-VA-MD-WV",47900,2018,120,83,37,0,0,0,0,79,61,43,0,0,33,0,87,0
301,"Waterloo-Cedar Falls, IA",47940,2018,120,55,65,0,0,0,0,81,66,52,0,0,19,0,101,0
302,"Watertown-Fort Drum, NY",48060,2018,28,28,0,0,0,0,0,44,40,35,0,0,28,0,0,0
303,"Weatherford, OK",48220,2018,90,88,2,0,0,0,0,65,32,18,0,0,0,0,0,90
304,"Weirton-Steubenville, WV-OH",48260,2018,90,55,35,0,0,0,0,83,62,48,0,0,3,16,65,6
305,"Wenatchee, WA",48300,2018,31,22,9,0,0,0,0,64,60,43,0,0,0,0,31,0
306,"Wheeling, WV-OH",48540,2018,90,56,34,0,0,0,0,93,68,44,0,0,21,0,69,0
307,"Williston, ND",48780,2018,87,76,11,0,0,0,0,68,53,33,0,0,30,0,55,2
308,"Wilmington, NC",48900,2018,87,85,2,0,0,0,0,56,25,12,0,0,0,0,87,0
309,"Wilmington, OH",48940,2018,31,31,0,0,0,0,0,45,44,38,0,0,31,0,0,0
310,"Winchester, VA-WV",49020,2018,30,25,5,0,0,0,0,85,57,23,0,0,0,0,20,10
311,"Winston-Salem, NC",49180,2018,89,70,19,0,0,0,0,73,56,33,0,1,0,0,88,0
312,"Worcester, MA-CT",49340,2018,90,75,15,0,0,0,0,73,54,41,0,4,57,0,29,0
313,"Yakima, WA",49420,2018,31,19,12,0,0,0,0,81,64,45,0,0,0,0,31,0
314,"Youngstown-Warren-Boardman, OH-PA",49660,2018,90,84,6,0,0,0,0,78,46,36,0,0,54,0,36,0
315,"Yuma, AZ",49740,2018,90,72,16,2,0,0,0,130,59,44,0,0,54,0,6,30

In [205]:
population

,Id,Id2,Geography,Estimate; Total,Margin of Error; Total
0,310M300US10180,10180,"Abilene, TX Metro Area",169747,2733
1,310M300US10420,10420,"Akron, OH Metro Area",703505,*****
2,310M300US10500,10500,"Albany, GA Metro Area",151754,1560
3,310M300US10540,10540,"Albany, OR Metro Area",125047,*****
4,310M300US10580,10580,"Albany-Schenectady-Troy, NY Metro Area",886188,*****
5,310M300US10740,10740,"Albuquerque, NM Metro Area",913113,2419
6,310M300US10780,10780,"Alexandria, LA Metro Area",153984,*****
7,310M300US10900,10900,"Allentown-Bethlehem-Easton, PA-NJ Metro Area",840550,*****
8,310M300US11020,11020,"Altoona, PA Metro Area",123457,*****
9,310M300US11100,11100,"Amarillo, TX Metro Area",266575,2127
10,310M300US11180,11180,"Ames, IA Metro Area",97502,*****
11,310M300US11260,11260,"Anchorage, AK Metro Area",400888,*****
12,310M300US11460,11460,"Ann Arbor, MI Metro Area",367627,*****
13,310M300US11500,11500,"Anniston-Oxford-Jacksonville, AL Metro Area",114728,*****
14,310M300US11540,11540,"Appleton, WI Metro Area",236126,*****
15,310M300US11700,11700,"Asheville, NC Metro Area",456145,*****
16,310M300US12020,12020,"Athens-Clarke County, GA Metro Area",206937,1995
17,310M300US12060,12060,"Atlanta-Sandy Springs-Roswell, GA Metro Area",5882450,2613
18,310M300US12100,12100,"Atlantic City-Hammonton, NJ Metro Area",269918,*****
19,310M300US12220,12220,"Auburn-Opelika, AL Metro Area",161604,*****
20,310M300US12260,12260,"Augusta-Richmond County, GA-SC Metro Area",600600,1969
21,310M300US12420,12420,"Austin-Round Rock, TX Metro Area",2115827,*****
22,310M300US12540,12540,"Bakersfield, CA Metro Area",893119,*****
23,310M300US12580,12580,"Baltimore-Columbia-Towson, MD Metro Area",2808175,*****
24,310M300US12620,12620,"Bangor, ME Metro Area",151957,*****
25,310M300US12700,12700,"Barnstable Town, MA Metro Area",213444,*****
26,310M300US12940,12940,"Baton Rouge, LA Metro Area",834159,*****
27,310M300US12980,12980,"Battle Creek, MI Metro Area",134128,*****
28,310M300US13020,13020,"Bay City, MI Metro Area",104239,*****
29,310M300US13140,13140,"Beaumont-Port Arthur, TX Metro Area",411339,2426
...,...,...,...,...,...
352,310M300US46520,46520,"Urban Honolulu, HI Metro Area",988650,*****
353,310M300US46540,46540,"Utica-Rome, NY Metro Area",293572,*****
354,310M300US46660,46660,"Valdosta, GA Metro Area",145871,1448
355,310M300US46700,46700,"Vallejo-Fairfield, CA Metro Area",445458,*****
356,310M300US47020,47020,"Victoria, TX Metro Area",100228,1664
357,310M300US47220,47220,"Vineland-Bridgeton, NJ Metro Area",152538,*****
358,310M300US47260,47260,"Virginia Beach-Norfolk-Newport News, VA-NC Met...",1724388,3765
359,310M300US47300,47300,"Visalia-Porterville, CA Metro Area",464493,*****
360,310M300US47380,47380,"Waco, TX Metro Area",267554,2227
361,310M300US47460,47460,"Walla Walla, WA Metro Area",64831,874
362,310M300US47580,47580,"Warner Robins, GA Metro Area",192766,2475
363,310M300US47900,47900,"Washington-Arlington-Alexandria, DC-VA-MD-WV M...",6216710,2604
364,310M300US47940,47940,"Waterloo-Cedar Falls, IA Metro Area",169892,*****
365,310M300US48060,48060,"Watertown-Fort Drum, NY Metro Area",114187,*****
366,310M300US48140,48140,"Wausau, WI Metro Area",135732,*****
367,310M300US48260,48260,"Weirton-Steubenville, WV-OH Metro Area",119664,2012
368,310M300US48300,48300,"Wenatchee, WA Metro Area",118478,*****
369,310M300US48540,48540,"Wheeling, WV-OH Metro Area",141254,*****
370,310M300US48620,48620,"Wichita, KS Metro Area",646542,1152
371,310M300US48660,48660,"Wichita Falls, TX Metro Area",151230,*****
372,310M300US48700,48700,"Williamsport, PA Metro Area",113841,*****
373,310M300US48900,48900,"Wilmington, NC Metro Area",288156,*****
374,310M300US49020,49020,"Winchester, VA-WV Metro Area",139223,2617
375,310M300US49180,49180,"Winston-Salem, NC Metro Area",667733,*****
376,310M300US49340,49340,"Worcester, MA-CT Metro Area",942475,*****
377,310M300US49420,49420,"Yakima, WA Metro Area",250193,*****
378,310M300US49620,49620,"York-Hanover, PA Metro Area",446078,*****
379,310M300US49660,49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",541926,*****
380,310M300US49700,49700,"Yuba City, CA Metro Area",173679,*****
381,310M300US49740,49740,"Yuma, AZ Metro Area",207534,*****

In [206]:
crosswalk

,CBSA Code,Metropolitan Division Code,CSA Code,CBSA Title,Metropolitan/Micropolitan Statistical Area,Metropolitan Division Title,CSA Title,County/County Equivalent,State Name,FIPS State Code,FIPS County Code,Central/Outlying County
0,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Brown County,South Dakota,46.0,13.0,Central
1,10100,NaN,NaN,"Aberdeen, SD",Micropolitan Statistical Area,NaN,NaN,Edmunds County,South Dakota,46.0,45.0,Outlying
2,10140,NaN,NaN,"Aberdeen, WA",Micropolitan Statistical Area,NaN,NaN,Grays Harbor County,Washington,53.0,27.0,Central
3,10180,NaN,NaN,"Abilene, TX",Metropolitan Statistical Area,NaN,NaN,Callahan County,Texas,48.0,59.0,Outlying
4,10180,NaN,NaN,"Abilene, TX",Metropolitan Statistical Area,NaN,NaN,Jones County,Texas,48.0,253.0,Outlying
5,10180,NaN,NaN,"Abilene, TX",Metropolitan Statistical Area,NaN,NaN,Taylor County,Texas,48.0,441.0,Central
6,10220,NaN,NaN,"Ada, OK",Micropolitan Statistical Area,NaN,NaN,Pontotoc County,Oklahoma,40.0,123.0,Central
7,10300,NaN,220.0,"Adrian, MI",Micropolitan Statistical Area,NaN,"Detroit-Warren-Ann Arbor, MI",Lenawee County,Michigan,26.0,91.0,Central
8,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Aguada Municipio,Puerto Rico,72.0,3.0,Central
9,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Aguadilla Municipio,Puerto Rico,72.0,5.0,Central
10,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Añasco Municipio,Puerto Rico,72.0,11.0,Central
11,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Isabela Municipio,Puerto Rico,72.0,71.0,Central
12,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Lares Municipio,Puerto Rico,72.0,81.0,Central
13,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Moca Municipio,Puerto Rico,72.0,99.0,Central
14,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Rincón Municipio,Puerto Rico,72.0,117.0,Central
15,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,San Sebastián Municipio,Puerto Rico,72.0,131.0,Central
16,10380,NaN,NaN,"Aguadilla-Isabela, PR",Metropolitan Statistical Area,NaN,NaN,Utuado Municipio,Puerto Rico,72.0,141.0,Central
17,10420,NaN,184.0,"Akron, OH",Metropolitan Statistical Area,NaN,"Cleveland-Akron-Canton, OH",Portage County,Ohio,39.0,133.0,Central
18,10420,NaN,184.0,"Akron, OH",Metropolitan Statistical Area,NaN,"Cleveland-Akron-Canton, OH",Summit County,Ohio,39.0,153.0,Central
19,10460,NaN,NaN,"Alamogordo, NM",Micropolitan Statistical Area,NaN,NaN,Otero County,New Mexico,35.0,35.0,Central
20,10500,NaN,NaN,"Albany, GA",Metropolitan Statistical Area,NaN,NaN,Dougherty County,Georgia,13.0,95.0,Central
21,10500,NaN,NaN,"Albany, GA",Metropolitan Statistical Area,NaN,NaN,Lee County,Georgia,13.0,177.0,Central
22,10500,NaN,NaN,"Albany, GA",Metropolitan Statistical Area,NaN,NaN,Terrell County,Georgia,13.0,273.0,Outlying
23,10500,NaN,NaN,"Albany, GA",Metropolitan Statistical Area,NaN,NaN,Worth County,Georgia,13.0,321.0,Outlying
24,10540,NaN,440.0,"Albany-Lebanon, OR",Metropolitan Statistical Area,NaN,"Portland-Vancouver-Salem, OR-WA",Linn County,Oregon,41.0,43.0,Central
25,10580,NaN,104.0,"Albany-Schenectady-Troy, NY",Metropolitan Statistical Area,NaN,"Albany-Schenectady, NY",Albany County,New York,36.0,1.0,Central
26,10580,NaN,104.0,"Albany-Schenectady-Troy, NY",Metropolitan Statistical Area,NaN,"Albany-Schenectady, NY",Rensselaer County,New York,36.0,83.0,Central
27,10580,NaN,104.0,"Albany-Schenectady-Troy, NY",Metropolitan Statistical Area,NaN,"Albany-Schenectady, NY",Saratoga County,New York,36.0,91.0,Central
28,10580,NaN,104.0,"Albany-Schenectady-Troy, NY",Metropolitan Statistical Area,NaN,"Albany-Schenectady, NY",Schenectady County,New York,36.0,93.0,Central
29,10580,NaN,104.0,"Albany-Schenectady-Troy, NY",Metropolitan Statistical Area,NaN,"Albany-Schenectady, NY",Schoharie County,New York,36.0,95.0,Outlying
...,...,...,...,...,...,...,...,...,...,...,...,...
1889,49180,NaN,268.0,"Winston-Salem, NC",Metropolitan Statistical Area,NaN,"Greensboro--Winston-Salem--High Point, NC",Davie County,North Carolina,37.0,59.0,Central
1890,49180,NaN,268.0,"Winston-Salem, NC",Metropolitan Statistical Area,NaN,"Greensboro--Winston-Salem--High Point, NC",Forsyth County,North Carolina,37.0,67.0,Central
1891,49180,NaN,268.0,"Winston-Salem, NC",Metropolitan Statistical Area,NaN,"Greensboro--Winston-Salem--High Point, NC",Stokes County,North Carolina,37.0,169.0,Central
1892,49180,NaN,268.0,"Winston-Salem, NC",Metropolitan Statistical Area,NaN,"Greensboro--Winston-Salem--High Point, NC",Yadkin County,North Carolina,37.0,197.0,Outlying
1893,49220,NaN,554.0,"Wisconsin Rapids-Marshfield, WI",Micropolitan Statistical Area,NaN,"Wausau-Stevens Point-Wisconsin Rapids, WI",Wood County,Wisconsin,55.0,141.0,Central
1894,49260,NaN,NaN,"Woodward, OK",Micropolitan Statistical Area,NaN,NaN,Ellis County,Oklahoma,40.0,45.0,Outlying
1895,49260,NaN,NaN,"Woodward, OK",Micropolitan Statistical Area,NaN,NaN,Woodward County,Oklahoma,40.0,153.0,Central
1896,49300,NaN,184.0,"Wooster, OH",Micropolitan Statistical Area,NaN,"Cleveland-Akron-Canton, OH",Wayne County,Ohio,39.0,169.0,Central
1897,49340,NaN,148.0,"Worcester, MA-CT",Metropolitan Statistical Area,NaN,"Boston-Worcester-Providence, MA-RI-NH-CT",Windham County,Connecticut,9.0,15.0,Central
1898,49340,NaN,148.0,"Worcester, MA-CT",Metropolitan Statistical Area,NaN,"Boston-Worcester-Providence, MA-RI-NH-CT",Worcester County,Massachusetts,25.0,27.0,Central
1899,49380,NaN,NaN,"Worthington, MN",Micropolitan Statistical Area,NaN,NaN,Nobles County,Minnesota,27.0,105.0,Central
1900,49420,NaN,NaN,"Yakima, WA",Metropolitan Statistical Area,NaN,NaN,Yakima County,Washington,53.0,77.0,Central
1901,49460,NaN,NaN,"Yankton, SD",Micropolitan Statistical Area,NaN,NaN,Yankton County,South Dakota,46.0,135.0,Central
1902,49500,NaN,434.0,"Yauco, PR",Metropolitan Statistical Area,NaN,"Ponce-Yauco-Coamo, PR",Guánica Municipio,Puerto Rico,72.0,55.0,Central
1903,49500,NaN,434.0,"Yauco, PR",Metropolitan Statistical Area,NaN,"Ponce-Yauco-Coamo, PR",Guayanilla Municipio,Puerto Rico,72.0,59.0,Central
1904,49500,NaN,434.0,"Yauco, PR",Metropolitan Statistical Area,NaN,"Ponce-Yauco-Coamo, PR",Peñuelas Municipio,Puerto Rico,72.0,111.0,Central
1905,49500,NaN,434.0,"Yauco, PR",Metropolitan Statistical Area,NaN,"Ponce-Yauco-Coamo, PR",Yauco Municipio,Puerto Rico,72.0,153.0,Central
1906,49620,NaN,276.0,"York-Hanover, PA",Metropolitan Statistical Area,NaN,"Harrisburg-York-Lebanon, PA",York County,Pennsylvania,42.0,133.0,Central
1907,49660,NaN,566.0,"Youngstown-Warren-Boardman, OH-PA",Metropolitan Statistical Area,NaN,"Youngstown-Warren, OH-PA",Mahoning County,Ohio,39.0,99.0,Central
1908,49660,NaN,566.0,"Youngstown-Warren-Boardman, OH-PA",Metropolitan Statistical Area,NaN,"Youngstown-Warren, OH-PA",Trumbull County,Ohio,39.0,155.0,Central
1909,49660,NaN,566.0,"Youngstown-Warren-Boardman, OH-PA",Metropolitan Statistical Area,NaN,"Youngstown-Warren, OH-PA",Mercer County,Pennsylvania,42.0,85.0,Central
1910,49700,NaN,472.0,"Yuba City, CA",Metropolitan Statistical Area,NaN,"Sacramento-Roseville, CA",Sutter County,California,6.0,101.0,Central
1911,49700,NaN,472.0,"Yuba City, CA",Metropolitan Statistical Area,NaN,"Sacramento-Roseville, CA",Yuba County,California,6.0,115.0,Central
1912,49740,NaN,NaN,"Yuma, AZ",Metropolitan Statistical Area,NaN,NaN,Yuma County,Arizona,4.0,27.0,Central
1913,49780,NaN,198.0,"Zanesville, OH",Micropolitan Statistical Area,NaN,"Columbus-Marion-Zanesville, OH",Muskingum County,Ohio,39.0,119.0,Central
1914,49820,NaN,NaN,"Zapata, TX",Micropolitan Statistical Area,NaN,NaN,Zapata County,Texas,48.0,505.0,Central
1915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1916,Note: The 2010 OMB Standards for Delineating M...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917,"Source: File prepared by U.S. Census Bureau, P...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1918,Internet Release Date: October 2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [207]:
smoking_drinking

,Year,Locationabbr,Locationdesc,Class,Topic,Question,Response,Break_Out,Break_Out_Category,Sample_Size,Data_value,Confidence_limit_Low,Confidence_limit_High,Display_order,Data_value_unit,Data_value_type,Data_Value_Footnote_Symbol,Data_Value_Footnote,DataSource,ClassId,TopicId,LocationID,BreakoutID,BreakOutCategoryID,QuestionID,RESPONSEID,GeoLocation
0,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Overall Health,How is your general health?,Excellent,Overall,Overall,85,16.63,11.57,21.69,1,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic41,10020,BO1,CAT1,GENHLTH,RESP056,"(29.7868663, -92.290084)"
1,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Overall Health,How is your general health?,Very good,Overall,Overall,153,34.55,26.28,42.82,2,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic41,10020,BO1,CAT1,GENHLTH,RESP057,"(29.7868663, -92.290084)"
2,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Overall Health,How is your general health?,Good,Overall,Overall,152,29.12,20.93,37.31,3,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic41,10020,BO1,CAT1,GENHLTH,RESP058,"(29.7868663, -92.290084)"
3,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Overall Health,How is your general health?,Fair,Overall,Overall,80,13.22,9.36,17.08,4,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic41,10020,BO1,CAT1,GENHLTH,RESP059,"(29.7868663, -92.290084)"
4,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Overall Health,How is your general health?,Poor,Overall,Overall,43,6.49,3.30,9.68,5,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic41,10020,BO1,CAT1,GENHLTH,RESP060,"(29.7868663, -92.290084)"
5,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Fair or Poor Health,Health Status (variable calculated from one or...,Good or Better Health,Overall,Overall,390,80.30,75.28,85.32,6,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic24,10020,BO1,CAT1,_RFHLTH,RESP061,"(29.7868663, -92.290084)"
6,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Status,Fair or Poor Health,Health Status (variable calculated from one or...,Fair or Poor Health,Overall,Overall,123,19.70,14.68,24.72,7,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS08,Topic24,10020,BO1,CAT1,_RFHLTH,RESP062,"(29.7868663, -92.290084)"
7,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Care Access/Coverage,Health Care Coverage,Do you have any kind of health care coverage?,Yes,Overall,Overall,448,84.01,78.13,89.89,8,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,Topic29,10020,BO1,CAT1,HLTHPLN1,RESP046,"(29.7868663, -92.290084)"
8,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Care Access/Coverage,Health Care Coverage,Do you have any kind of health care coverage?,No,Overall,Overall,64,15.99,10.11,21.87,9,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,Topic29,10020,BO1,CAT1,HLTHPLN1,RESP054,"(29.7868663, -92.290084)"
9,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Care Access/Coverage,Under 65 Coverage,Adults aged 18-64 who have any kind of health ...,Yes,Overall,Overall,270,80.58,73.39,87.77,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,Topic59,10020,BO1,CAT1,_HCVU651,RESP046,"(29.7868663, -92.290084)"
10,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Health Care Access/Coverage,Under 65 Coverage,Adults aged 18-64 who have any kind of health ...,No,Overall,Overall,63,19.42,12.23,26.61,11,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,Topic59,10020,BO1,CAT1,_HCVU651,RESP054,"(29.7868663, -92.290084)"
11,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Physical Activity,Exercise,"During the past month, did you participate in ...",Yes,Overall,Overall,311,67.56,59.78,75.34,12,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS15,Topic23,10020,BO1,CAT1,_TOTINDA,RESP046,"(29.7868663, -92.290084)"
12,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Physical Activity,Exercise,"During the past month, did you participate in ...",No,Overall,Overall,186,32.44,24.66,40.22,13,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS15,Topic23,10020,BO1,CAT1,_TOTINDA,RESP054,"(29.7868663, -92.290084)"
13,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Hypertension Awareness,High Blood Pressure,Adults who have been told they have high blood...,Yes,Overall,Overall,238,33.58,26.97,40.19,14,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS10,Topic31,10020,BO1,CAT1,_RFHYPE5,RESP046,"(29.7868663, -92.290084)"
14,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Hypertension Awareness,High Blood Pressure,Adults who have been told they have high blood...,No,Overall,Overall,277,66.42,59.81,73.03,15,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS10,Topic31,10020,BO1,CAT1,_RFHYPE5,RESP054,"(29.7868663, -92.290084)"
15,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol Checked,Adults who have ever had their blood cholester...,Yes,Overall,Overall,452,75.37,66.49,84.25,16,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,Topic11,10020,BO1,CAT1,BLOODCHO,RESP046,"(29.7868663, -92.290084)"
16,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol Checked,Adults who have ever had their blood cholester...,No,Overall,Overall,56,24.63,15.75,33.51,17,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,Topic11,10020,BO1,CAT1,BLOODCHO,RESP054,"(29.7868663, -92.290084)"
17,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol Checked,Adults who have had their blood cholesterol ch...,Checked in past 5 years,Overall,Overall,432,70.59,61.20,79.98,18,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,Topic11,10020,BO1,CAT1,_CHOLCHK,RESP072,"(29.7868663, -92.290084)"
18,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Demographics,Disability status,Adults with health problem(s) that requires th...,Yes,Overall,Overall,49,7.22,4.36,10.08,70,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,Topic19,10020,BO1,CAT1,USEEQUIP,RESP046,"(29.7868663, -92.290084)"
19,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol Checked,Adults who have had their blood cholesterol ch...,Not Checked in past 5 years,Overall,Overall,12,NaN,NaN,NaN,19,%,Crude Prevalence,*,Prevalence estimate not available if the unwei...,BRFSS,CLASS02,Topic11,10020,BO1,CAT1,_CHOLCHK,RESP073,"(29.7868663, -92.290084)"
20,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol Checked,Adults who have had their blood cholesterol ch...,Never Checked,Overall,Overall,56,25.01,16.01,34.01,20,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,Topic11,10020,BO1,CAT1,_CHOLCHK,RESP074,"(29.7868663, -92.290084)"
21,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol High,Adults who have had their blood cholesterol ch...,Yes,Overall,Overall,189,35.20,28.87,41.53,21,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,Topic12,10020,BO1,CAT1,_RFCHOL,RESP046,"(29.7868663, -92.290084)"
22,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Cholesterol Awareness,Cholesterol High,Adults who have had their blood cholesterol ch...,No,Overall,Overall,263,64.80,58.47,71.13,22,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,Topic12,10020,BO1,CAT1,_RFCHOL,RESP054,"(29.7868663, -92.290084)"
23,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had a heart attack (myocardial i...,Yes,Overall,Overall,37,5.13,2.50,7.76,23,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic10,10020,BO1,CAT1,CVDINFR4,RESP046,"(29.7868663, -92.290084)"
24,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had a heart attack (myocardial i...,No,Overall,Overall,476,94.87,92.24,97.50,24,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic10,10020,BO1,CAT1,CVDINFR4,RESP054,"(29.7868663, -92.290084)"
25,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had angina or coronary heart dis...,Yes,Overall,Overall,42,6.01,3.19,8.83,25,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic10,10020,BO1,CAT1,CVDCRHD4,RESP046,"(29.7868663, -92.290084)"
26,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had angina or coronary heart dis...,No,Overall,Overall,467,93.99,91.17,96.81,26,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic10,10020,BO1,CAT1,CVDCRHD4,RESP054,"(29.7868663, -92.290084)"
27,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had a stroke?,Yes,Overall,Overall,34,4.94,2.29,7.59,27,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic10,10020,BO1,CAT1,CVDSTRK3,RESP046,"(29.7868663, -92.290084)"
28,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had a stroke?,No,Overall,Overall,481,95.06,92.41,97.71,28,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic10,10020,BO1,CAT1,CVDSTRK3,RESP054,"(29.7868663, -92.290084)"
29,2011,10020,"Abbeville, LA Micropolitan Statistical Area",Chronic Health Indicators,Asthma,Adults who have ever been told they have asthm...,Yes,Overall,Overall,49,10.30,6.30,14.30,29,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,Topic06,10020,BO1,CAT1,_LTASTH1,RESP046,"(29.7868663, -92.290084)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120029,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Chronic Health Indicators,Cardiovascular Disease,Ever told you had a stroke?,No,Overall,Overall,1377,96.40,94.68,98.12,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,TOPIC10,49340,BO1,CAT1,CVDSTRK3,RESP054,"(42.3116848, -71.9402811)"
120030,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Hearing,Adults who reported being deaf,No,Overall,Overall,1243,92.83,90.73,94.93,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC70,49340,BO1,CAT1,DEAF,RESP054,"(42.3116848, -71.9402811)"
120031,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Disability status,"Do you have serious difficulty concentrating, ...",No,Overall,Overall,1237,86.07,82.52,89.62,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC19,49340,BO1,CAT1,DECIDE,RESP054,"(42.3116848, -71.9402811)"
120032,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Chronic Health Indicators,Diabetes,Have you ever been told by a doctor that you h...,No,Overall,Overall,1219,86.13,82.97,89.29,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,TOPIC18,49340,BO1,CAT1,DIABETE3,RESP054,"(42.3116848, -71.9402811)"
120033,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Disability status,Do you have difficulty doing errands alone?,No,Overall,Overall,1276,90.87,87.91,93.83,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC19,49340,BO1,CAT1,DIFFALON,RESP054,"(42.3116848, -71.9402811)"
120034,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Disability status,Do you have difficulty dressing or bathing?,No,Overall,Overall,1323,95.24,93.38,97.10,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC19,49340,BO1,CAT1,DIFFDRES,RESP054,"(42.3116848, -71.9402811)"
120035,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Disability status,Do you have serious difficulty walking or clim...,No,Overall,Overall,1151,85.18,81.97,88.39,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC19,49340,BO1,CAT1,DIFFWALK,RESP054,"(42.3116848, -71.9402811)"
120036,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Alcohol Consumption,Alcohol Consumption,Adults who have had at least one drink of alco...,No,Overall,Overall,509,42.36,37.52,47.20,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS01,TOPIC03,49340,BO1,CAT1,DRNKANY5,RESP054,"(42.3116848, -71.9402811)"
120037,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",HIV-AIDS,HIV Test,Have you ever been tested for HIV?,No,Overall,Overall,864,64.05,59.17,68.93,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS09,TOPIC32,49340,BO1,CAT1,HIVTST6,RESP054,"(42.3116848, -71.9402811)"
120038,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Health Care Access/Coverage,Health Care Coverage,Do you have any kind of health care coverage?,No,Overall,Overall,75,6.90,4.27,9.53,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,TOPIC29,49340,BO1,CAT1,HLTHPLN1,RESP054,"(42.3116848, -71.9402811)"
120039,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Internet,Have you used the internet in the past 30 days?,No,Overall,Overall,245,15.36,12.20,18.52,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC34,49340,BO1,CAT1,INTERNET,RESP054,"(42.3116848, -71.9402811)"
120040,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Health Care Access/Coverage,Health Care Cost,Was there a time in the past 12 months when yo...,No,Overall,Overall,1310,91.23,88.51,93.95,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,TOPIC28,49340,BO1,CAT1,MEDCOST,RESP054,"(42.3116848, -71.9402811)"
120041,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Health Care Access/Coverage,Personal Care Provider,Do you have one person you think of as your pe...,No,Overall,Overall,131,11.78,8.68,14.88,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,TOPIC43,49340,BO1,CAT1,PERSDOC2,RESP054,"(42.3116848, -71.9402811)"
120042,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Immunization,Shingle Vaccination,Have you ever had the shingles or zoster vaccine?,No,Overall,Overall,591,73.34,67.42,79.26,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS11,TOPIC63,49340,BO1,CAT1,SHINGLE2,RESP054,"(42.3116848, -71.9402811)"
120043,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Demographics,Veteran Status,Have you ever served on active duty in the Uni...,No,Overall,Overall,1256,88.81,85.87,91.75,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS05,TOPIC61,49340,BO1,CAT1,VETERAN3,RESP054,"(42.3116848, -71.9402811)"
120044,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Chronic Health Indicators,Asthma,Adults who have been told they currently have ...,No,Overall,Overall,1215,85.02,81.43,88.61,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,TOPIC06,49340,BO1,CAT1,_CASTHM1,RESP054,"(42.3116848, -71.9402811)"
120045,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Chronic Health Indicators,Arthritis,Adults who have been told they have arthritis ...,No,Overall,Overall,915,71.97,67.74,76.20,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,TOPIC05,49340,BO1,CAT1,_DRDXAR1,RESP054,"(42.3116848, -71.9402811)"
120046,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Immunization,Flu Shot,Adults aged 65+ who have had a flu shot within...,No,Overall,Overall,167,42.91,33.03,52.79,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS11,TOPIC26,49340,BO1,CAT1,_FLSHOT6,RESP054,"(42.3116848, -71.9402811)"
120047,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Health Care Access/Coverage,Under 65 Coverage,Adults aged 18-64 who have any kind of health ...,No,Overall,Overall,68,8.16,4.91,11.41,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS07,TOPIC59,49340,BO1,CAT1,_HCVU651,RESP054,"(42.3116848, -71.9402811)"
120048,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Chronic Health Indicators,Asthma,Adults who have ever been told they have asthm...,No,Overall,Overall,1158,80.22,76.32,84.12,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS03,TOPIC06,49340,BO1,CAT1,_LTASTH1,RESP054,"(42.3116848, -71.9402811)"
120049,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Physical Activity,Aerobic Activity,Participated in 150 minutes or more of Aerobic...,No,Overall,Overall,609,50.13,45.07,55.19,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS15,TOPIC01,49340,BO1,CAT1,_PAINDX1,RESP054,"(42.3116848, -71.9402811)"
120050,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Physical Activity,Physical Activity Index,Participated in enough Aerobic and Muscle Stre...,No,Overall,Overall,984,80.42,76.46,84.38,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS15,TOPIC45,49340,BO1,CAT1,_PASTAE1,RESP054,"(42.3116848, -71.9402811)"
120051,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Physical Activity,Strength Activity,Participated in muscle strengthening exercises...,No,Overall,Overall,892,67.48,62.76,72.20,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS15,TOPIC56,49340,BO1,CAT1,_PASTRNG,RESP054,"(42.3116848, -71.9402811)"
120052,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Immunization,Pneumonia Vaccination,Adults aged 65+ who have ever had a pneumonia ...,No,Overall,Overall,90,21.74,13.78,29.70,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS11,TOPIC46,49340,BO1,CAT1,_PNEUMO2,RESP054,"(42.3116848, -71.9402811)"
120053,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Alcohol Consumption,Binge Drinking,Binge drinkers (males having five or more drin...,No,Overall,Overall,1149,82.66,78.98,86.34,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS01,TOPIC07,49340,BO1,CAT1,_RFBING5,RESP054,"(42.3116848, -71.9402811)"
120054,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Cholesterol Awareness,Cholesterol High,Adults who have had their blood cholesterol ch...,No,Overall,Overall,493,30.99,26.44,35.54,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS02,TOPIC12,49340,BO1,CAT1,_RFCHOL1,RESP054,"(42.3116848, -71.9402811)"
120055,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Hypertension Awareness,High Blood Pressure,Adults who have been told they have high blood...,No,Overall,Overall,876,69.79,65.58,74.00,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS10,TOPIC31,49340,BO1,CAT1,_RFHYPE5,RESP054,"(42.3116848, -71.9402811)"
120056,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Injury,Seatbelt Use,Always or nearly always wears a seat belt?,No,Overall,Overall,68,6.29,3.76,8.82,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS12,TOPIC50,49340,BO1,CAT1,_RFSEAT2,RESP054,"(42.3116848, -71.9402811)"
120057,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Tobacco Use,Current Smoker Status,Adults who are current smokers (variable calcu...,No,Overall,Overall,1187,84.68,81.05,88.31,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS17,TOPIC15,49340,BO1,CAT1,_RFSMOK3,RESP054,"(42.3116848, -71.9402811)"
120058,2017,49340,"Worcester, MA-CT Metropolitan Statistical Area",Physical Activity,Exercise,"During the past month, did you participate in ...",No,Overall,Overall,350,26.26,21.93,30.59,10,%,Crude Prevalence,NaN,NaN,BRFSS,CLASS15,TOPIC23,49340,BO1,CAT1,_TOTINDA,RESP054,"(42.3116848, -71.9402811)"

In [208]:
smoking_drinking['Question'].unique()

array(['How is your general health?',
       'Health Status (variable calculated from one or more BRFSS questions)',
       'Do you have any kind of health care coverage?',
       'Adults aged 18-64 who have any kind of health care coverage (variable calculated from one or more BRFSS questions)',
       'During the past month, did you participate in any physical activities? (variable calculated from one or more BRFSS questions)',
       'Adults who have been told they have high blood pressure (variable calculated from one or more BRFSS questions)',
       'Adults who have ever had their blood cholesterol checked',
       'Adults who have had their blood cholesterol checked within the last five years (variable calculated from one or more BRFSS questions)',
       'Adults with health problem(s) that requires the use of special equipment',
       'Adults who have had their blood cholesterol checked and have been told it was high (variable calculated from one or more BRFSS questions)',
       'Ever told you had a heart attack (myocardial infarction)?',
       'Ever told you had angina or coronary heart disease?',
       'Ever told you had a stroke?',
       'Adults who have ever been told they have asthma (variable calculated from one or more BRFSS questions)',
       'Adults who have been told they currently have asthma (variable calculated from one or more BRFSS questions)',
       'Adults who have been told they have arthritis (variable calculated from one or more BRFSS questions)',
       'Have you ever been told by a doctor that you have diabetes?',
       'Ever told you had skin cancer?',
       'Ever told you had any other types of cancer?',
       'Ever told you have COPD?', 'Ever told you have kidney disease?',
       'Ever told you have vision impairment?',
       'Ever told you that you have a form of depression?',
       'Adults who are current smokers (variable calculated from one or more BRFSS questions)',
       'Four Level Smoking Status (variable calculated from one or more BRFSS questions)',
       'Weight classification by Body Mass Index (BMI) (variable calculated from one or more BRFSS questions)',
       'Participated in 150 minutes or more of Aerobic Physical Activity per week (variable calculated from one or more BRFSS questions)',
       'Participated in muscle strengthening exercises two or more times per week (variable calculated from one or more BRFSS questions).',
       'Participated in enough Aerobic and Muscle Strengthening exercises to meet guidelines (variable calculated from one or more BRFSS questions)',
       'Adults who are limited in any activities because of physical, mental, or emotional problems',
       'Always wears a seat belt? (variable calculated from one or more BRFSS questions)',
       'Adults aged 65+ who have had a flu shot within the past year (variable calculated from one or more BRFSS questions)',
       'Adults aged 65+ who have ever had a pneumonia vaccination (variable calculated from one or more BRFSS questions)',
       'Adults who have had at least one drink of alcohol within the past 30 days',
       'Binge drinkers (males having five or more drinks on one occasion, females having four or more drinks on one occasion) (variable calculated from one or more BRFSS questions)',
       'Heavy drinkers (adult men having more than two drinks per day and adult women having more than one drink per day) (variable calculated from one or more BRFSS questions)',
       'Adults that have had any permanent teeth extracted (variable calculated from one or more BRFSS questions)',
       'Adults aged 65+ who have had all their natural teeth extracted (variable calculated from one or more BRFSS questions)',
       'Visited the dentist or dental clinic within the past year for any reason (variable calculated from one or more BRFSS questions)',
       'Respondents who have reported having driven after drinking too much (variable calculated from one or more BRFSS questions)',
       'Women aged 40+ who have had a mammogram within the past two years (variable calculated from one or more BRFSS questions)',
       'Women aged 50+ who have had a mammogram within the past two years (variable calculated from one or more BRFSS questions)',
       'Women aged 18+ who have had a pap test within the past three years (variable calculated from one or more BRFSS questions)',
       'Men aged 40+ who have had a PSA test within the past two years (variable calculated from one or more BRFSS questions)',
       'Adults aged 50+ who have had a blood stool test within the past two years (variable calculated from one or more BRFSS questions)',
       'Adults aged 50+ who have ever had a sigmoidoscopy or colonoscopy (variable calculated from one or more BRFSS questions)',
       'Do you have one person you think of as your personal doctor or health care provider?',
       'Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?',
       'About how long has it been since you last visited a doctor for a routine checkup?',
       'Have you ever served on active duty in the United States Armed Forces?',
       'Have you used the internet in the past 30 days?',
       'Do you own or rent your home?',
       'Are you blind or do you have serious difficulty seeing, even when wearing glasses?',
       'Do you have serious difficulty concentrating, remembering, or making decisions?',
       'Do you have serious difficulty walking or climbing stairs?',
       'Do you have difficulty dressing or bathing?',
       'Do you have difficulty doing errands alone?',
       'Do you currently use chewing tobacco, snuff, or snus?',
       'Consumed fruit less than one time per day (variable calculated from one or more BRFSS questions)',
       'Consumed vegetables less than one time per day (variable calculated from one or more BRFSS questions)',
       'Are you now limited in any way in any of your usual activities because of arthritis? (variable calculated from one or more BRFSS questions)',
       'Do arthritis or joint symptoms now affect whether you work? (variable calculated from one or more BRFSS questions)',
       'Does arthritis or joint symptoms interfere with your normal social activities? (variable calculated from one or more BRFSS questions)',
       'Since 2005, have you had a tetanus shot?',
       'Have you ever been tested for HIV?',
       'Have you ever had the shingles or zoster vaccine?',
       'Women aged 50-74 who have had a mammogram within the past two years (variable calculated from one or more BRFSS questions)',
       'Women aged 21-65 who have had a pap test in the past three years (variable calculated from one or more BRFSS questions)',
       'Adults aged 50-75 who have had a blood stool test within the past year (variable calculated from one or more BRFSS questions)',
       'Respondents aged 50-75 who have fully met the USPSTF recommendation (variable calculated from one or more BRFSS questions)',
       'Respondents that have ever reported having coronary heart disease (chd) or myocardial infarction (mi) (variable calculated from one or more BRFSS questions)',
       'Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) (variable calculated from one or more BRFSS questions)',
       'Adults who reported being deaf',
       'Aged 50-75 had a colonoscopy in the past 10 years',
       'Current E-cigarette user', 'E-cigarette use status',
       'Aged 50-75 had a blood stool test within the past 3 years',
       'Aged 50-75 had a sigmoidoscopy within the past 5 years',
       'Always or nearly always wears a seat belt?',
       'Participated in muscle strengthening exercises two or more times per week (variable calculated from one or more BRFSS questions)'],
      dtype=object)

Alright, data is loaded up, now let's do some preliminary cleaning so we can merge.

The biggest pain is going to be dealing with the FBI crime data. It doesn't appear as if it has any CBSA code associated with it, so we're going to have to match on the metro area name after we do some hacky string manipulation. It's going to really suck to manage, but it's gotta get done.

Also our definition of 'excessive drinking' is fuzzy. We have a few different questions we can draw from: 
- 'Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week) (variable calculated from one or more BRFSS questions)'
- 'Heavy drinkers (adult men having more than two drinks per day and adult women having more than one drink per day) (variable calculated from one or more BRFSS questions)'
- 'Binge drinkers (males having five or more drinks on one occasion, females having four or more drinks on one occasion) (variable calculated from one or more BRFSS questions)'
- 'Respondents who have reported having driven after drinking too much (variable calculated from one or more BRFSS questions)'

For smoking, we'll use this question:
- 'Adults who are current smokers (variable calculated from one or more BRFSS questions)'

Here's another problem: the population statistics proided by the Census Bureau aren't even close to the ones offered by the CDC in their accidental death data. Which set should we use?

In [209]:
#Cleaning accidental death data
accidental_death = accidental_death.iloc[:188,1:]
accidental_death = accidental_death.drop(['Crude Rate', 'Deaths'],axis=1)
accidental_death.rename(columns={
    '2013 CBSA Code' : 'CBSA Code',
    'Age Adjusted Rate' : 'Age Adjusted Accidental Death Rate per 100000'
}, inplace=True)

In [210]:
#Clean air quality data
airq = airq[['CBSA Code', 'Median AQI']]

In [211]:
#Clean population data
population = population[['Id2', 'Estimate; Total']]
population.rename(columns={
    'Id2' : 'CBSA Code'
}, inplace=True)

C:\Users\spenc\Anaconda3\lib\site-packages\pandas\core\frame.py:3027: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [212]:
#Extract the relevant questions from the smoking_drinking dataset
#using the most recent year available;
#construct new columns and append to the dataframe.
smoking = smoking_drinking.loc[
    (smoking_drinking['Question'] == 'Adults who are current smokers (variable calculated from one or more BRFSS questions)') &
    (smoking_drinking['Response'] == 'Yes')
][['Year', 'Locationabbr', 'Data_value']]
smoking.rename(columns={
    'Locationabbr' : 'CBSA Code',
    'Data_value' : 'Smoking rate'
},inplace=True)

#De-dupe by location code, most recent year
for ID in smoking['CBSA Code'].unique():
    max_year = max(smoking.loc[
        smoking['CBSA Code'] == ID
    ]['Year'])
    smoking.drop(smoking.loc[
        (smoking['CBSA Code'] == ID) &
        ~(smoking['Year'] == max_year)
    ].index, axis=0, inplace=True)
    
drinking = smoking_drinking.loc[
    (smoking_drinking['Question'] == 'Binge drinkers (males having five or more drinks on one occasion, females having four or more drinks on one occasion) (variable calculated from one or more BRFSS questions)') &
    (smoking_drinking['Response'] == 'Yes')
][['Year', 'Locationabbr', 'Data_value']]
drinking.rename(columns={
    'Locationabbr' : 'CBSA Code',
    'Data_value' : 'Binge drinking rate'
},inplace=True)

for ID in drinking['CBSA Code'].unique():
    max_year = max(drinking.loc[
        drinking['CBSA Code'] == ID
    ]['Year'])
    drinking.drop(drinking.loc[
        (drinking['CBSA Code'] == ID) &
        ~(drinking['Year'] == max_year)
    ].index, axis=0, inplace=True)
    
drinking.drop(columns=['Year'], axis=1,inplace=True)

In [213]:
#Merge our datasets
DATASETS = [accidental_death, airq, population, smoking, drinking]
merged = reduce(lambda x,y: x.merge(y, on='CBSA Code', how='inner'), DATASETS)

In [214]:
merged

,2013 CBSA,CBSA Code,Population,Age Adjusted Accidental Death Rate per 100000,Median AQI,Estimate; Total,Year,Smoking rate,Binge drinking rate
0,"Akron, OH",10420,12625850.0,36.8,37,703505,2015,27.80,20.38
1,"Albany-Schenectady-Troy, NY",10580,15466849.0,22.5,40,886188,2017,15.77,15.62
2,"Asheville, NC",11700,7379094.0,49.3,43,456145,2012,23.26,12.85
3,"Atlanta-Sandy Springs-Roswell, GA",12060,90449335.0,38.0,42,5882450,2017,14.93,13.61
4,"Augusta-Richmond County, GA-SC",12260,9876079.0,45.4,44,600600,2017,16.74,13.43
5,"Baltimore-Columbia-Towson, MD",12580,48206323.0,27.3,44,2808175,2017,15.42,17.11
6,"Baton Rouge, LA",12940,13890020.0,48.1,46,834159,2017,21.69,20.49
7,"Birmingham-Hoover, AL",13820,19871028.0,52.7,47,1149807,2017,19.70,12.14
8,"Boulder, CO",14500,5340377.0,45.3,41,322514,2012,13.53,15.42
9,"Buffalo-Cheektowaga-Niagara Falls, NY",15380,20634485.0,28.1,41,1136856,2017,20.38,26.45
10,"Canton-Massillon, OH",15940,7287867.0,37.6,41,399927,2012,26.65,15.02
11,"Cedar Rapids, IA",16300,4545321.0,35.8,43,270293,2017,18.08,22.91
12,"Charleston-North Charleston, SC",16700,11505391.0,44.1,39,775831,2017,18.85,22.62
13,"Charlotte-Concord-Gastonia, NC-SC",16740,37458020.0,41.8,44,2525305,2017,14.57,17.86
14,"Chattanooga, TN-GA",16860,9249007.0,45.5,40,554876,2016,21.11,11.42
15,"Chicago-Naperville-Elgin, IL-IN-WI",16980,168325749.0,29.5,53,9533895,2017,13.60,19.88
16,"Cincinnati, OH-KY-IN",17140,37467088.0,44.2,45,2180746,2017,23.49,21.44
17,"Cleveland-Elyria, OH",17460,37752896.0,33.8,44,2058844,2017,21.89,21.93
18,"Colorado Springs, CO",17820,11137645.0,43.8,43,723878,2017,16.09,15.62
19,"Columbia, SC",17900,13175878.0,45.4,43,825004,2017,16.91,17.16
20,"Columbus, OH",18140,33290879.0,38.4,39,2078725,2017,20.31,20.06
21,"Davenport-Moline-Rock Island, IA-IL",19340,6800374.0,35.2,52,382298,2013,18.94,21.43
22,"Dayton, OH",19380,14447964.0,55.4,41,803416,2017,19.77,18.90
23,"Denver-Aurora-Lakewood, CO",19740,44331118.0,44.0,51,2888227,2017,13.76,20.62
24,"Des Moines-West Des Moines, IA",19780,9881430.0,34.6,41,645911,2017,14.42,21.51
25,"Duluth, MN-WI",20260,5004136.0,44.7,39,278782,2017,21.54,23.52
26,"Durham-Chapel Hill, NC",20500,8748691.0,35.9,33,567428,2013,14.60,14.44
27,"Evansville, IN-KY",21780,5525055.0,44.2,38,315669,2017,22.99,17.63
28,"Fayetteville, NC",22180,6426652.0,44.8,28,386662,2012,22.48,11.69
29,"Fayetteville-Springdale-Rogers, AR-MO",22220,7810873.0,39.8,38,535557,2017,17.07,15.48
...,...,...,...,...,...,...,...,...,...
66,"Providence-Warwick, RI-MA",39300,28872395.0,36.6,42,1621122,2017,15.32,17.24
67,"Provo-Orem, UT",39340,8716146.0,35.2,36,617678,2017,4.20,4.77
68,"Raleigh, NC",39580,18726744.0,34.8,36,1335079,2016,12.46,15.75
69,"Richmond, VA",40060,21046257.0,38.1,24,1301540,2017,17.35,18.57
70,"Riverside-San Bernardino-Ontario, CA",40140,71562879.0,31.5,47,4580670,2017,11.06,19.33
71,"Roanoke, VA",40220,5436453.0,42.0,6,312688,2014,22.56,14.49
72,"Rochester, NY",40380,19345310.0,28.6,39,1077948,2017,17.26,15.52
73,"Sacramento--Roseville--Arden-Arcade, CA",40900,37285686.0,34.4,40,2324884,2017,9.45,17.63
74,"St. Louis, MO-IL",41180,49541012.0,45.4,44,2807216,2017,19.35,21.22
75,"Salisbury, MD-DE",41540,6435204.0,38.7,37,405853,2017,18.27,13.16
76,"Salt Lake City, UT",41620,18889750.0,38.2,44,1203105,2017,10.38,15.71
77,"San Diego-Carlsbad, CA",41740,54665674.0,30.1,11,3337685,2012,10.57,19.00
78,"San Francisco-Oakland-Hayward, CA",41860,77464278.0,26.2,53,4727357,2011,11.71,20.85
79,"San Jose-Sunnyvale-Santa Clara, CA",41940,32640337.0,23.3,40,1998463,2016,5.89,11.76
80,"Shreveport-Bossier City, LA",43340,7777221.0,46.6,39,440933,2014,25.01,15.42
81,"South Bend-Mishawaka, IN-MI",43780,5728087.0,36.1,33,321815,2017,21.13,19.15
82,"Spartanburg, SC",43900,5476055.0,53.1,42,334391,2017,18.25,11.64
83,"Spokane-Spokane Valley, WA",44060,9185708.0,54.1,55,564291,2017,16.86,13.71
84,"Springfield, MA",44140,11154049.0,29.8,42,631652,2017,18.49,20.83
85,"Syracuse, NY",45060,11829668.0,35.8,38,654841,2016,19.43,19.91
86,"Tampa-St. Petersburg-Clearwater, FL",45300,48653674.0,50.2,50,3091399,2017,18.39,16.50
87,"Toledo, OH",45780,11031944.0,40.1,35,603668,2017,19.82,21.99
88,"Trenton, NJ",45940,6536429.0,27.8,30,374733,2012,14.97,15.66
89,"Tucson, AZ",46060,16938659.0,48.8,39,1022769,2012,16.41,17.47
90,"Tulsa, OK",46140,16478278.0,52.9,47,990773,2017,19.95,14.71
91,"Utica-Rome, NY",46540,5367579.0,29.1,39,293572,2016,17.45,18.50
92,"Virginia Beach-Norfolk-Newport News, VA-NC",47260,29854379.0,32.9,21,1724388,2017,16.21,19.01
93,"Winston-Salem, NC",49180,11146868.0,45.7,33,667733,2013,26.55,11.52
94,"Worcester, MA-CT",49340,16262459.0,32.4,41,942475,2017,15.32,17.34
95,"Youngstown-Warren-Boardman, OH-PA",49660,10353629.0,44.8,36,541926,2014,24.67,15.61

In [215]:
'''
Alright, time for the ugly part.

To extract all of the FBI data, we're going to have to:
    1) Find every row that doesn't have NaN for Metropolitan Statistical Area
    2) Add 4 to the index to get the row with 'Rate per 100,000 inhabitants' under 'Counties/principal cities'
        (Side note: whose bright idea was that?)
    3) Extract the 'Violent Crime' and 'Property Crime' values, if they exist
        Create a corner case for when they don't!
    4) Pull the 'Metropolitan Statistical Area' string and extract the location in the format <METRO>, <STATE>
    5) Match that against the string we have under '2013 CBSA' in the merged table'

...simple enough, right?
'''

#First, cut down the number of rows in the crime dataset
crime = crime.iloc[:2331,:]

#Extract the indices of rows that have the metro name
metro_indices = crime[pd.notnull(crime['Metropolitan Statistical Area'])].index

#Find the rate per 100,000 for each metro area
final_metro_indices = []
violent_crime_rate = []
property_crime_rate = []
for x in range(len(metro_indices)):
    #Get metro index in dataframe, figure out where to stop looking for the rate
    index = metro_indices[x]
    next_index = metro_indices[x + 1] if not x == (len(metro_indices) - 1) else len(crime)
    
    #Search the bounded range for the rate
    for rate_index in range(index, next_index):
        row = crime.iloc[rate_index, :]
        if row['Counties/principal cities'] == 'Rate per 100,000 inhabitants' and not np.isnan(row['Violent\ncrime']) and not np.isnan(row['Property\ncrime']):
            final_metro_indices.append(index)
            violent_crime_rate.append(row['Violent\ncrime'])
            property_crime_rate.append(row['Property\ncrime'])
            break

#Sanity check on the number of values for indices and crime rates
assert(len(final_metro_indices) == len(violent_crime_rate))
assert(len(violent_crime_rate) == len(property_crime_rate))

#Strip down the metro names so that we can match against the merged dataframe
metro_names = []
for index in final_metro_indices:
    name = crime.iloc[index,:]['Metropolitan Statistical Area']
    name = name.split(' M.S.A.')[0]
    metro_names.append(name)

#Build the dataframe for 
crime_df = pd.DataFrame(data={
    '2013 CBSA' : metro_names,
    'Violent crime rate per 100,000' : violent_crime_rate,
    'Property crime rate per 100,000' : property_crime_rate
})

In [216]:
crime_df

,2013 CBSA,"Property crime rate per 100,000","Violent crime rate per 100,000"
0,"Akron, OH",2541.0,277.3
1,"Albany, GA",3937.1,726.6
2,"Albany, OR",2547.3,158.0
3,"Albany-Schenectady-Troy, NY",1954.7,291.2
4,"Albuquerque, NM",5498.9,1084.9
5,"Alexandria, LA",4763.9,729.0
6,"Allentown-Bethlehem-Easton, PA-NJ",1667.0,237.5
7,"Altoona, PA",1419.5,202.7
8,"Amarillo, TX",3588.4,634.1
9,"Ames, IA",1934.7,181.2
10,"Anchorage, AK",5441.4,1162.8
11,"Ann Arbor, MI",1634.3,326.9
12,"Anniston-Oxford-Jacksonville, AL",2867.9,860.3
13,"Appleton, WI",1233.4,140.5
14,"Athens-Clarke County, GA",2574.5,307.8
15,"Atlanta-Sandy Springs-Roswell, GA",2865.7,367.6
16,"Atlantic City-Hammonton, NJ",2557.4,312.0
17,"Auburn-Opelika, AL M.S.A",2706.1,552.0
18,"Austin-Round Rock, TX",2344.4,306.3
19,"Bakersfield, CA",3246.6,559.8
20,"Baltimore-Columbia-Towson, MD",2732.9,782.5
21,"Bangor, ME",1588.7,65.8
22,"Barnstable Town, MA",1368.0,355.3
23,"Baton Rouge, LA",3937.5,546.8
24,"Battle Creek, MI M.S.A",2958.9,684.3
25,"Bay City, MI",1905.9,368.4
26,"Beckley, WV M.S.A",2195.8,311.3
27,"Bellingham, WA M.S.A",2964.9,225.3
28,"Bend-Redmond, OR",1991.8,175.0
29,"Billings, MT",4176.6,396.9
...,...,...,...
320,"Vineland-Bridgeton, NJ",3553.9,520.9
321,"Virginia Beach-Norfolk-Newport News, VA-NC",2633.7,330.8
322,"Visalia-Porterville, CA",2542.8,359.7
323,"Waco, TX",2785.8,459.0
324,"Walla Walla, WA",2639.0,335.5
325,"Warner Robins, GA",3726.3,376.1
326,"Washington-Arlington-Alexandria, DC-VA-MD-WV",1745.4,273.4
327,"Silver Spring-Frederick-Rockville, MD M.D.2",1309.9,166.0
328,"Washington-Arlington-Alexandria, DC-VA-MD-WV M.D.",1861.3,302.0
329,"Waterloo-Cedar Falls, IA",2005.4,318.0
330,"Watertown-Fort Drum, NY",1773.3,206.4
331,"Wausau, WI",1061.1,159.7
332,"Weirton-Steubenville, WV-OH",1801.5,141.2
333,"Wenatchee, WA",1736.1,117.5
334,"Wheeling, WV-OH",1341.9,363.0
335,"Wichita Falls, TX",2724.2,333.0
336,"Williamsport, PA",1638.5,183.2
337,"Winchester, VA-WV",1626.9,203.5
338,"Worcester, MA-CT",1344.3,360.2
339,"Yakima, WA",3234.6,355.4
340,"York-Hanover, PA",1457.5,246.5
341,"Yuba City, CA",2850.9,386.6
342,"Yuma, AZ",2081.7,350.4
343,"Aguadilla-Isabela, Puerto Rico",613.7,163.6
344,"Arecibo, Puerto Rico",649.6,176.7
345,"Guayama, Puerto Rico",657.8,229.8
346,"Mayaguez, Puerto Rico",895.6,178.0
347,"Ponce, Puerto Rico",760.9,277.2
348,"San German, Puerto Rico",364.0,111.8
349,"San Juan-Carolina-Caguas, Puerto Rico",1093.9,254.7

In [217]:
merged = merged.merge(crime_df, on='2013 CBSA', how='inner')

In [218]:
merged

,2013 CBSA,CBSA Code,Population,Age Adjusted Accidental Death Rate per 100000,Median AQI,Estimate; Total,Year,Smoking rate,Binge drinking rate,"Property crime rate per 100,000","Violent crime rate per 100,000"
0,"Akron, OH",10420,12625850.0,36.8,37,703505,2015,27.80,20.38,2541.0,277.3
1,"Albany-Schenectady-Troy, NY",10580,15466849.0,22.5,40,886188,2017,15.77,15.62,1954.7,291.2
2,"Atlanta-Sandy Springs-Roswell, GA",12060,90449335.0,38.0,42,5882450,2017,14.93,13.61,2865.7,367.6
3,"Baltimore-Columbia-Towson, MD",12580,48206323.0,27.3,44,2808175,2017,15.42,17.11,2732.9,782.5
4,"Baton Rouge, LA",12940,13890020.0,48.1,46,834159,2017,21.69,20.49,3937.5,546.8
5,"Buffalo-Cheektowaga-Niagara Falls, NY",15380,20634485.0,28.1,41,1136856,2017,20.38,26.45,2185.8,375.7
6,"Cedar Rapids, IA",16300,4545321.0,35.8,43,270293,2017,18.08,22.91,2410.0,217.4
7,"Charlotte-Concord-Gastonia, NC-SC",16740,37458020.0,41.8,44,2525305,2017,14.57,17.86,2800.4,416.2
8,"Chattanooga, TN-GA",16860,9249007.0,45.5,40,554876,2016,21.11,11.42,3394.1,557.3
9,"Cincinnati, OH-KY-IN",17140,37467088.0,44.2,45,2180746,2017,23.49,21.44,2440.8,264.9
10,"Colorado Springs, CO",17820,11137645.0,43.8,43,723878,2017,16.09,15.62,2614.8,431.8
11,"Columbus, OH",18140,33290879.0,38.4,39,2078725,2017,20.31,20.06,2865.6,290.7
12,"Davenport-Moline-Rock Island, IA-IL",19340,6800374.0,35.2,52,382298,2013,18.94,21.43,2833.6,404.2
13,"Dayton, OH",19380,14447964.0,55.4,41,803416,2017,19.77,18.90,2553.9,294.3
14,"Duluth, MN-WI",20260,5004136.0,44.7,39,278782,2017,21.54,23.52,3007.3,201.8
15,"Evansville, IN-KY",21780,5525055.0,44.2,38,315669,2017,22.99,17.63,2785.7,373.8
16,"Fort Collins, CO",22660,5225574.0,37.4,46,343976,2012,15.74,17.99,2242.9,239.8
17,"Fort Smith, AR-OK",22900,4883412.0,48.9,31,282086,2013,25.44,12.06,2949.3,506.3
18,"Grand Rapids-Wyoming, MI",24340,17699673.0,38.3,11,1059113,2017,14.49,19.88,1516.6,324.0
19,"Greeley, CO",24540,4258691.0,45.3,44,304633,2012,20.56,17.77,1739.3,256.3
20,"Greenville-Anderson-Mauldin, SC",24860,14351469.0,52.7,42,895923,2017,17.62,12.60,3101.8,486.8
21,"Hagerstown-Martinsburg, MD-WV",25180,4312705.0,42.3,38,265498,2017,21.06,15.15,1657.2,295.9
22,"Huntington-Ashland, WV-KY-OH",26580,6528934.0,63.4,29,356474,2017,24.25,10.12,2193.5,306.9
23,"Indianapolis-Carmel-Anderson, IN",26900,32939176.0,36.1,43,2027059,2017,19.37,17.13,2882.4,694.5
24,"Kennewick-Richland, WA",28420,4251915.0,34.9,22,290296,2015,13.52,18.92,2045.4,205.0
25,"Kingsport-Bristol-Bristol, TN-VA",28700,5482591.0,51.7,28,305914,2017,31.66,9.79,2492.7,354.8
26,"Knoxville, TN",28940,14602847.0,57.0,40,877874,2017,27.26,13.33,2596.9,440.1
27,"Lansing-East Lansing, MI",29620,8320952.0,33.9,10,477656,2017,20.21,21.27,1952.7,432.5
28,"Las Vegas-Henderson-Paradise, NV",29820,32448616.0,40.6,51,2204079,2012,16.98,13.78,2779.2,607.9
29,"Little Rock-North Little Rock-Conway, AR",30780,12131813.0,42.5,39,738082,2017,24.82,18.16,4088.2,798.6
...,...,...,...,...,...,...,...,...,...,...,...
36,"Mobile, AL",33660,7320274.0,51.2,17,413955,2012,25.71,15.43,4555.2,619.0
37,"Myrtle Beach-Conway-North Myrtle Beach, SC-NC",34820,6291478.0,57.4,38,464165,2017,20.53,13.61,3609.3,415.6
38,"New Orleans-Metairie, LA",35380,22599954.0,50.6,44,1275762,2017,21.72,19.52,2948.1,564.0
39,"Ogden-Clearfield, UT",36260,10172408.0,35.7,44,666547,2017,9.51,10.73,2095.7,162.3
40,"Oklahoma City, OK",36420,21907918.0,49.5,44,1383737,2017,17.13,14.72,2897.9,498.4
41,"Olympia-Tumwater, WA",36500,4315530.0,37.9,8,280588,2012,23.27,18.71,2559.2,270.1
42,"Omaha-Council Bluffs, NE-IA",36540,15125277.0,33.0,47,934184,2017,16.60,20.64,2764.9,384.5
43,"Phoenix-Mesa-Scottsdale, AZ",38060,71259632.0,45.0,62,4737270,2017,14.84,15.98,2815.3,470.6
44,"Pittsburgh, PA",38300,42786147.0,44.6,46,2333367,2017,21.26,19.38,1573.1,278.2
45,"Portland-South Portland, ME",38860,9189623.0,37.9,43,532083,2017,13.70,18.73,1476.9,127.4
46,"Providence-Warwick, RI-MA",39300,28872395.0,36.6,42,1621122,2017,15.32,17.24,1691.5,294.9
47,"Provo-Orem, UT",39340,8716146.0,35.2,36,617678,2017,4.20,4.77,1530.0,79.8
48,"Riverside-San Bernardino-Ontario, CA",40140,71562879.0,31.5,47,4580670,2017,11.06,19.33,2489.8,383.3
49,"Roanoke, VA",40220,5436453.0,42.0,6,312688,2014,22.56,14.49,2389.5,229.8
50,"Rochester, NY",40380,19345310.0,28.6,39,1077948,2017,17.26,15.52,1927.9,283.0
51,"Salisbury, MD-DE",41540,6435204.0,38.7,37,405853,2017,18.27,13.16,2547.9,393.3
52,"Salt Lake City, UT",41620,18889750.0,38.2,44,1203105,2017,10.38,15.71,4434.6,400.6
53,"San Diego-Carlsbad, CA",41740,54665674.0,30.1,11,3337685,2012,10.57,19.00,1695.5,337.1
54,"San Jose-Sunnyvale-Santa Clara, CA",41940,32640337.0,23.3,40,1998463,2016,5.89,11.76,2275.1,308.8
55,"Shreveport-Bossier City, LA",43340,7777221.0,46.6,39,440933,2014,25.01,15.42,3832.4,606.9
56,"Spokane-Spokane Valley, WA",44060,9185708.0,54.1,55,564291,2017,16.86,13.71,4473.1,322.1
57,"Springfield, MA",44140,11154049.0,29.8,42,631652,2017,18.49,20.83,2170.7,503.8
58,"Syracuse, NY",45060,11829668.0,35.8,38,654841,2016,19.43,19.91,2051.7,267.8
59,"Tampa-St. Petersburg-Clearwater, FL",45300,48653674.0,50.2,50,3091399,2017,18.39,16.50,2101.6,333.1
60,"Trenton, NJ",45940,6536429.0,27.8,30,374733,2012,14.97,15.66,1875.3,371.8
61,"Tucson, AZ",46060,16938659.0,48.8,39,1022769,2012,16.41,17.47,3928.2,499.0
62,"Tulsa, OK",46140,16478278.0,52.9,47,990773,2017,19.95,14.71,3431.4,565.7
63,"Utica-Rome, NY",46540,5367579.0,29.1,39,293572,2016,17.45,18.50,1731.8,287.2
64,"Virginia Beach-Norfolk-Newport News, VA-NC",47260,29854379.0,32.9,21,1724388,2017,16.21,19.01,2633.7,330.8
65,"Worcester, MA-CT",49340,16262459.0,32.4,41,942475,2017,15.32,17.34,1344.3,360.2

OK, we weren't left with very many cities after the merge. Let's see if we can figure out why.

In [219]:
print("Accidental death: ", len(accidental_death))
print("Crime: ", len(crime))
print("Air quality: ", len(airq))
print("Population: ", len(population))
print("Smoking and drinking: ", len(smoking_drinking))

Accidental death:  188
Crime:  2331
Air quality:  316
Population:  382
Smoking and drinking:  120059

In [220]:
merged.to_csv('output/merged.csv')

In [221]:
len(
    smoking.merge(
        drinking, 
        on='CBSA Code', 
        how='inner'
    ).merge(
        accidental_death, 
        on='CBSA Code', 
        how='inner'
    ).merge(
        airq,
        on='CBSA Code',
        how='inner'
    ).merge(
        population,
        on='CBSA Code',
        how='inner'
    ).merge(
        crime_df,
        on='2013 CBSA',
        how='inner'
    )
)

66

In [222]:
len(merged.loc[
    merged['Estimate; Total'] > 100000
])

66